pages mv error resolved.2

diff --git a/.github/workflows/rss-site.yml b/.github/workflows/rss-site.yml
--- a/.github/workflows/rss-site.yml
+++ b/.github/workflows/rss-site.yml
@@ -81,3 +81,7 @@ jobs:
           git add .
           git commit -m "🚀 Deploy GitHub Pages"
           git push -f origin gh-pages
+      - name: Debug Output Folder
+        run: |
+          echo "Listing output/"
+          ls -l output || echo "output/ not found"
