pages mv error resolved.

diff --git a/.github/workflows/rss-site.yml b/.github/workflows/rss-site.yml
--- a/.github/workflows/rss-site.yml
+++ b/.github/workflows/rss-site.yml
@@ -68,7 +68,11 @@ jobs:
       - name: Deploy output/ to gh-pages branch
         run: |
           rm -rf .gitignore .github
-          mkdir temp && mv output/* temp/
+          if [ -d output ]; then
+            mkdir temp && mv output/* temp/
+          else
+            echo "❌ output/ directory not found. Exiting..." && exit 1
+          fi
           git checkout --orphan gh-pages
           git rm -rf .
           mv temp/* .
